server:
  port: 8801

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'


spring:
  application:
    name: data-center
  datasource:
    url: jdbc:postgresql://localhost:5432/data_center
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: com.umasuo.database.dialect.JSONBPostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: localhsot

device:
  center:
    service:
      url: http://localhost:8082/devices/
data:
  definition:
    service:
      url: http://localhost:8802/

message:
  broker:
    host: 127.0.0.1
    port: 1883
    username: umasuo
    password: password